=head1 NAME

Nempire

=head1 DESCRIPTION

empireenterprises.com website

=head1 PURPOSE

=over 4

=item * CRUD blog

=item * Fetch & Display photos from Flickr

=item * Comments on blog & photos

=item * Display facebook & twitter statii

=back

=head1 VERSION

5.0

=head1 AUTHOR

Glen Hinkle

=cut
